apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "test-workshop"
spec:
  title: "Workshop"
  description: "Workshop description."
  publish:
    image: "$(image_repository)/test-workshop-files:$(workshop_version)"
  workshop:
    image: "docker.io/samarsinghal/test-workshop:latest"
    files:
    - git:
        url: "https://github.com/samarsinghal/test-workshop"
        ref: origin/main
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false
